name: rosetta-stone
channels:
  - conda-forge
  - defaults
dependencies:
  - _r-mutex=1.0.1
  - appnope=0.1.0
  - attrs=19.3.0
  - backcall=0.1.0
  - bleach=3.1.0
  - bwidget=1.9.13
  - bzip2=1.0.8
  - ca-certificates=2019.9.11
  - cairo=1.16.0
  - cctools=895
  - certifi=2019.9.11
  - clang=4.0.1
  - clang_osx-64=4.0.1
  - clangxx=4.0.1
  - clangxx_osx-64=4.0.1
  - compiler-rt=4.0.1
  - curl=7.65.3
  - decorator=4.4.0
  - defusedxml=0.6.0
  - entrypoints=0.3
  - fontconfig=2.13.1
  - freetype=2.10.0
  - gettext=0.19.8.1
  - gfortran_osx-64=4.8.5
  - glib=2.58.3
  - graphite2=1.3.13
  - gsl=2.4
  - harfbuzz=2.4.0
  - icu=58.2
  - importlib_metadata=0.23
  - ipykernel=5.1.2
  - ipython=7.8.0
  - ipython_genutils=0.2.0
  - ipywidgets=7.5.1
  - jedi=0.15.1
  - jinja2=2.10.3
  - joblib=0.14.0
  - jpeg=9c
  - jsonschema=3.1.1
  - jupyter=1.0.0
  - jupyter_client=5.3.3
  - jupyter_console=6.0.0
  - jupyter_core=4.5.0
  - krb5=1.16.3
  - ld64=274.2
  - libblas=3.8.0
  - libcblas=3.8.0
  - libcurl=7.65.3
  - libcxx=4.0.1
  - libcxxabi=4.0.1
  - libedit=3.1.20170329
  - libffi=3.2.1
  - libgfortran=3.0.1
  - libiconv=1.15
  - liblapack=3.8.0
  - libopenblas=0.3.7
  - libpng=1.6.37
  - libsodium=1.0.17
  - libssh2=1.8.2
  - libtiff=4.0.10
  - libxml2=2.9.9
  - llvm=4.0.1
  - llvm-lto-tapi=4.0.1
  - llvm-openmp=9.0.0
  - lz4-c=1.8.3
  - make=4.2.1
  - markupsafe=1.1.1
  - mistune=0.8.4
  - more-itertools=7.2.0
  - nbconvert=5.6.0
  - nbformat=4.4.0
  - ncurses=6.1
  - notebook=6.0.1
  - numpy=1.17.2
  - openssl=1.1.1c
  - pandas=0.25.1
  - pandoc=2.7.3
  - pandocfilters=1.4.2
  - pango=1.40.14
  - parso=0.5.1
  - pcre=8.41
  - pexpect=4.7.0
  - pickleshare=0.7.5
  - pip=19.2.3
  - pixman=0.38.0
  - prometheus_client=0.7.1
  - prompt_toolkit=2.0.10
  - ptyprocess=0.6.0
  - pygments=2.4.2
  - pyqt=5.6.0
  - pyrsistent=0.15.4
  - python=3.7.3
  - python-dateutil=2.8.0
  - pytz=2019.3
  - pyzmq=18.1.0
  - qt=5.6.2
  - qtconsole=4.5.5
  - r-askpass=1.1
  - r-assertthat=0.2.1
  - r-backports=1.1.5
  - r-base=3.5.1
  - r-base64enc=0.1_3
  - r-bh=1.69.0_1
  - r-boot=1.3_23
  - r-broom=0.5.2
  - r-callr=3.3.2
  - r-caret=6.0_84
  - r-cellranger=1.1.0
  - r-class=7.3_15
  - r-cli=1.1.0
  - r-clipr=0.7.0
  - r-cluster=2.1.0
  - r-codetools=0.2_16
  - r-colorspace=1.4_1
  - r-crayon=1.3.4
  - r-curl=4.2
  - r-data.table=1.12.4
  - r-dbi=1.0.0
  - r-dbplyr=1.4.2
  - r-digest=0.6.21
  - r-dplyr=0.8.3
  - r-ellipsis=0.3.0
  - r-essentials=3.5.1
  - r-evaluate=0.14
  - r-fansi=0.4.0
  - r-forcats=0.4.0
  - r-foreach=1.4.7
  - r-foreign=0.8_72
  - r-formatr=1.7
  - r-fs=1.3.1
  - r-generics=0.0.2
  - r-ggplot2=3.2.1
  - r-gistr=0.4.2
  - r-glmnet=2.0_18
  - r-glue=1.3.1
  - r-gower=0.2.1
  - r-gtable=0.3.0
  - r-haven=2.1.1
  - r-hexbin=1.27.3
  - r-highr=0.8
  - r-hms=0.5.1
  - r-htmltools=0.3.6
  - r-htmlwidgets=1.5.1
  - r-httpuv=1.5.2
  - r-httr=1.4.1
  - r-ipred=0.9_9
  - r-irdisplay=0.7
  - r-irkernel=1.0.2
  - r-iterators=1.0.12
  - r-jsonlite=1.6
  - r-kernsmooth=2.23_15
  - r-knitr=1.25
  - r-labeling=0.3
  - r-later=0.8.0
  - r-lattice=0.20_38
  - r-lava=1.6.6
  - r-lazyeval=0.2.2
  - r-lifecycle=0.1.0
  - r-lubridate=1.7.4
  - r-magrittr=1.5
  - r-maps=3.3.0
  - r-markdown=1.1
  - r-mass=7.3_51.4
  - r-matrix=1.2_17
  - r-mgcv=1.8_29
  - r-mime=0.7
  - r-modelmetrics=1.2.2
  - r-modelr=0.1.5
  - r-munsell=0.5.0
  - r-nlme=3.1_141
  - r-nnet=7.3_12
  - r-numderiv=2016.8_1.1
  - r-openssl=1.4.1
  - r-pbdzmq=0.3_3
  - r-pillar=1.4.2
  - r-pkgconfig=2.0.3
  - r-plogr=0.2.0
  - r-plyr=1.8.4
  - r-prettyunits=1.0.2
  - r-processx=3.4.1
  - r-prodlim=2018.04.18
  - r-progress=1.2.2
  - r-promises=1.0.1
  - r-pryr=0.1.4
  - r-ps=1.3.0
  - r-purrr=0.3.2
  - r-quantmod=0.4_15
  - r-r6=2.4.0
  - r-randomforest=4.6_14
  - r-rbokeh=0.5.0
  - r-rcolorbrewer=1.1_2
  - r-rcpp=1.0.2
  - r-readr=1.3.1
  - r-readxl=1.3.1
  - r-recipes=0.1.7
  - r-recommended=3.5.1
  - r-rematch=1.0.1
  - r-repr=1.0.1
  - r-reprex=0.3.0
  - r-reshape2=1.4.3
  - r-rlang=0.4.0
  - r-rmarkdown=1.16
  - r-rpart=4.1_15
  - r-rstudioapi=0.10
  - r-rvest=0.3.4
  - r-scales=1.0.0
  - r-selectr=0.4_1
  - r-shiny=1.3.2
  - r-sourcetools=0.1.7
  - r-spatial=7.3_11
  - r-squarem=2017.10_1
  - r-stringi=1.4.3
  - r-stringr=1.4.0
  - r-survival=2.44_1.1
  - r-sys=3.3
  - r-tibble=2.1.3
  - r-tidyr=1.0.0
  - r-tidyselect=0.2.5
  - r-tidyverse=1.2.1
  - r-timedate=3043.102
  - r-tinytex=0.16
  - r-ttr=0.23_5
  - r-utf8=1.1.4
  - r-uuid=0.1_2
  - r-vctrs=0.2.0
  - r-viridislite=0.3.0
  - r-whisker=0.4
  - r-withr=2.1.2
  - r-xfun=0.10
  - r-xml2=1.2.2
  - r-xtable=1.8_4
  - r-xts=0.11_2
  - r-yaml=2.2.0
  - r-zeallot=0.1.0
  - r-zoo=1.8_6
  - readline=7.0
  - scikit-learn=0.21.2
  - scipy=1.3.1
  - send2trash=1.5.0
  - setuptools=41.4.0
  - sip=4.18.1
  - six=1.12.0
  - sqlite=3.26.0
  - terminado=0.8.2
  - testpath=0.4.2
  - tk=8.6.9
  - tktable=2.10
  - tornado=6.0.3
  - traitlets=4.3.3
  - wcwidth=0.1.7
  - webencodings=0.5.1
  - wheel=0.33.6
  - widgetsnbextension=3.5.1
  - xz=5.2.4
  - zeromq=4.3.2
  - zipp=0.6.0
  - zlib=1.2.11
  - zstd=1.4.0

