name: rosetta-stone
channels:
  - conda-forge
  - defaults
dependencies:
  - ipykernel=5.1.2
  - ipython=7.8.0
  - ipython_genutils=0.2.0
  - ipywidgets=7.5.1
  - jupyter=1.0.0
  - jupyter_client=5.3.3
  - jupyter_console=6.0.0
  - jupyter_core=4.5.0
  - nbconvert=5.6.0
  - nbformat=4.4.0
  - notebook=6.0.1
  - numpy=1.17.2
  - pandas=0.25.1
  - python=3.7.3
  - r-base=3.5.1
  - r-data.table=1.12.4
  - r-dplyr=0.8.3
  - r-ggplot2=3.2.1
  - r-irdisplay=0.7
  - r-irkernel=1.0.2
  - r-magrittr=1.5
  - r-readr=1.3.1
  - r-tibble=2.1.3
  - scikit-learn=0.21.2
  - scipy=1.3.1
