name: rosetta-stone
channels:
  - conda-forge
dependencies:
  - black
  - jupyterlab
  - jupyterlab_code_formatter
  - nbautoexport
  - numpy
  - pandas
  - pip
  - plotnine
  - pyprojroot==0.2.0
  - python
  - r-base
  - r-data.table
  - r-dplyr
  - r-ggplot2
  - r-here
  - r-irdisplay
  - r-irkernel
  - r-magrittr
  - r-readr
  - r-styler
  - r-tibble
  - rpy2
  - scikit-learn
  - scipy
