name: rosetta-stone
channels:
  - conda-forge
dependencies:
  - ipywidgets
  - jupyterlab
  - nbautoexport
  - numpy
  - pandas
  - pip
  - pyprojroot==0.2.0
  - python
  - r-base
  - r-data.table
  - r-dplyr
  - r-ggplot2
  - r-here
  - r-irdisplay
  - r-irkernel
  - r-magrittr
  - r-readr
  - r-tibble
  - scikit-learn
  - scipy
