name: rosetta-stone
channels:
  - conda-forge
dependencies:
  - ipython
  - ipywidgets
  - jupyter
  - jupyterlab
  - nbconvert
  - numpy
  - pandas
  - python
  - r-base
  - r-data.table
  - r-dplyr
  - r-ggplot2
  - r-irdisplay
  - r-irkernel
  - r-magrittr
  - r-readr
  - r-tibble
  - scikit-learn
  - scipy
